openapi: 3.0.0
info:
  title: Encryption API
  version: 1.0.0
  description: This is the API specification for the ChatGPT Encryption Plugin. It provides an endpoint to encrypt data using various methods.
paths:
  /api/encrypt:
    post:
      summary: Encrypt data
      description: Encrypts a given string using the specified method and returns the encrypted data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                method:
                  type: string
                  enum: [AES, HMAC-SHA256, SHA256, MD5, hex, Base64, UTF8, PBKDF2, SHA1, HMAC-MD5]
                  description: The encryption method to use.
                input:
                  type: string
                  description: The input string to encrypt.
                input_format:
                  type: string
                  enum: [hex, Base64, utf-8]
                  description: The format of the input string.
                output_format:
                  type: string
                  enum: [hex, Base64, utf-8]
                  description: The desired format of the encrypted output.
                parameters:
                  type: object
                  properties:
                    aes_key:
                      type: string
                      description: The key to use for AES encryption.
              required: [method, input, input_format]
      responses:
        '200':
          description: A successful response, returning the encrypted data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string
                    description: The encrypted output.
                  encoding:
                    type: string
                    description: The encoding of the output.
